[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "odeal-sdk"
version = "0.1.4"
description = "Odeal Entegrasyon SDK (Otomatik Üretildi)"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"
authors = [
    { name = "Odeal" }
]
dependencies = [
    "requests>=2.31.0",
]

[project.urls]
"Homepage" = "https://github.com/odeal/sdk"

[tool.setuptools]
license-files = ["LICENSE"]

[tool.setuptools.packages.find]
where = ["src"]
